### ISSUE TITLE
Separate Commits for demo

### ISSUE THREAD

**Issue by drbyte** [LaravelDaily/Laravel-Datatables-Advanced#1]
Thanks for this demo!

Suggestion for future demo repositories:
First do a single commit with the base Laravel install.
THEN do a commit that adds the actual demo functionality.

This way people can more easily identify what files/changes are related to the demo you're making available ... without having to download and compare offline against a base Laravel install, etc.

Thanks for considering.

**Comment by PovilasKorop** [comment]
Hi @drbyte thanks for the suggestion. I thought about it, but it's not that simple, cause usually those demo projects are done by a few people within our team, making a lot of commits, or partly generate by our QuickAdminPanel, so there's no "base Laravel install" commit, and then I'm not sure people would benefit from all that "in progress" work commits.

**Comment by drbyte** [comment]
No worries. I completely understand how that goes! 

And in this case the datatables.net docs contain the examples anyway, so it's less of an issue in this case.
